services:
  - type: web
    name: discord-timer-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python myserver.py
    healthCheckPath: /
    envVars:
      - key: TOKEN
        sync: false
